export enum SlotUnavailableReason {
  CLINIC_HOLIDAY = 'CLINIC_HOLIDAY',
  DOCTOR_ON_LEAVE = 'DOCTOR_ON_LEAVE',
  NO_SCHEDULE = 'NO_SCHEDULE',
  ALL_SLOTS_BOOKED = 'ALL_SLOTS_BOOKED',
  CONSULTING_HOURS_OVER = 'CONSULTING_HOURS_OVER',
  PAST_DATE = 'PAST_DATE',
}